local M = {}

M.title = "Eltoto Neovim Shortcuts"

M.sections = {
    {
        title = "General",
        entries = {
            { lhs = "<leader>?", desc = "open the shortcuts popup" },
            { lhs = ":AIStatus", desc = "show OpenAI key visibility, Avante model, Codex availability, and Copilot status" },
            { lhs = ":EltotoHealth", desc = "run the Neovim health check for this config" },
            { lhs = ":TermimalConfig", desc = "open the runner popup for the current filetype and set default or session-only custom <leader>e behavior" },
            { lhs = ":TerminalRename", desc = "rename the current terminal buffer, or reset to default numbering with an empty name" },
            { lhs = ":TerminalProcesses", desc = "open the persistent terminal picker" },
            { lhs = ":TerminalProcessNew", desc = "create a new persistent terminal process" },
            { lhs = ":TerminalProcessKill", desc = "kill a persistent terminal process" },
            { lhs = ":TerminalProcessKillAll", desc = "kill all persistent terminal processes" },
            { lhs = ":TerminalProcessAttachLast", desc = "attach the last persistent terminal process" },
            { lhs = ":ShortcutsSync", desc = "regenerate SHORTCUTS.txt and the README shortcuts section" },
        },
    },
    {
        title = "AI",
        notes = {
            "Avante is configured to use OpenAI with the gpt-5.4 model.",
            "Copilot handles inline completions separately and authenticates through :Copilot setup.",
            "This config does not currently force a specific Copilot inline model from Neovim.",
        },
        entries = {
            { lhs = "<leader>aa", desc = "open Avante ask" },
            { lhs = "<leader>ac", desc = "open Avante chat" },
            { lhs = "<leader>at", desc = "toggle the Avante sidebar, or create a new chat if none exists" },
            { lhs = "visual <leader>aa", desc = "ask Avante about the current visual selection" },
            { lhs = "visual <leader>ae", desc = "send the current visual selection to Avante edit" },
            { lhs = "visual <leader>as", desc = "send the current visual selection to Avante edit" },
            { lhs = "Avante window <leader>an", desc = "start a new Avante chat" },
            { lhs = "Avante window <leader>ah", desc = "open the Avante chat history picker" },
            { lhs = "Avante window <leader>ac", desc = "clear the current Avante chat history" },
            { lhs = "Avante window <leader>ad", desc = "delete the currently active Avante chat" },
            { lhs = "Avante window <leader>aD", desc = "delete all saved Avante chats for the current project" },
            { lhs = "Avante window <leader>;", desc = "switch to the next Avante chat history entry" },
            { lhs = "Avante window <leader>,", desc = "switch to the previous Avante chat history entry" },
            { lhs = "Avante window <leader>z", desc = "toggle the Avante layout between split and full view" },
            { lhs = "Avante prompt <C-s>", desc = "submit the current Avante prompt or edit request" },
            { lhs = "insert <C-]>", desc = "accept the current Copilot inline suggestion" },
        },
    },
    {
        title = "Files and Search",
        entries = {
            { lhs = "<leader>pf", desc = "Telescope file picker" },
            { lhs = "<leader>ps", desc = "Telescope git-tracked file picker" },
            { lhs = "<leader>pg", desc = "grep for an entered string with Telescope" },
            { lhs = "<leader>bb", desc = "Telescope buffer picker" },
            { lhs = "<leader>pv", desc = "toggle the file explorer in a left vertical split" },
            { lhs = "<leader>w", desc = "save the current file" },
            { lhs = "qa", desc = "force quit the current window" },
            { lhs = "qq", desc = "close the current window if split, otherwise close the current buffer or quit Neovim when only terminal buffers remain" },
            { lhs = "<leader>ba", desc = "jump to the alternate or last file buffer" },
        },
    },
    {
        title = "Regular Buffer Navigation",
        entries = {
            { lhs = "<leader>;", desc = "jump to the next regular file buffer" },
            { lhs = "<leader>,", desc = "jump to the previous regular file buffer" },
        },
    },
    {
        title = "Terminal Workflow",
        entries = {
            { lhs = "<leader>t", desc = "toggle between the current file buffer and the last terminal buffer you used" },
            { lhs = "<leader>T", desc = "always open a new terminal buffer" },
            { lhs = "terminal <leader>;", desc = "jump to the next terminal buffer and stay in terminal input mode" },
            { lhs = "terminal <leader>,", desc = "jump to the previous terminal buffer and stay in terminal input mode" },
            { lhs = "terminal <leader>1", desc = "jump to buffer 1 from a terminal" },
            { lhs = "terminal <leader>r", desc = "rename the current terminal buffer" },
            { lhs = "terminal qq", desc = "close the current window if split, otherwise close the current terminal buffer or quit Neovim if no file buffers remain" },
            { lhs = "terminal jk", desc = "leave terminal input mode" },
            { lhs = "terminal buffers", desc = "default to T:1, T:2, T:3, ... and may be manually renamed" },
            { lhs = ":b T:1", desc = "jump directly to a named terminal buffer" },
        },
    },
    {
        title = "Persistent Processes",
        notes = {
            "Persistent processes use tmux as a hidden backend so they survive terminal buffer closes and Neovim restarts.",
            "Closing the attached terminal buffer detaches from the process; it does not kill the tmux session.",
        },
        entries = {
            { lhs = "<leader>pp", desc = "open the persistent terminal picker and attach to a selected process" },
            { lhs = "<leader>pn", desc = "create a new persistent terminal process" },
            { lhs = "<leader>pa", desc = "attach the last persistent terminal process" },
            { lhs = "<leader>pk", desc = "kill the current persistent terminal process, or select one to kill" },
            { lhs = "<leader>pK", desc = "kill all persistent terminal processes at once" },
        },
    },
    {
        title = "Run Current File",
        notes = {
            "<leader>e uses the current buffer filetype to pick a runner.",
            "Examples: python -> python3, lua -> lua, javascript -> node, typescript -> tsx, shell -> bash, go -> go run.",
            "Non-runnable filetypes like json, yaml, html, and markdown show a warning instead of trying to execute.",
            "Custom runner commands set through :TermimalConfig last only for the current Neovim session.",
        },
        entries = {
            { lhs = "<leader>e", desc = "open or reuse a terminal and run the current file with the resolved filetype runner" },
        },
    },
    {
        title = "Windows and Layout",
        entries = {
            { lhs = "<leader>h", desc = "move to the window on the left" },
            { lhs = "<leader>j", desc = "move to the window below" },
            { lhs = "<leader>k", desc = "move to the window above" },
            { lhs = "<leader>l", desc = "move to the window on the right" },
            { lhs = "<leader>sv", desc = "create a vertical split" },
            { lhs = "<leader>sh", desc = "create a horizontal split" },
            { lhs = "<leader>o", desc = "keep only the current window and close all other splits" },
            { lhs = "<leader>=", desc = "increase current window height" },
            { lhs = "<leader>-", desc = "decrease current window height" },
            { lhs = "W=", desc = "increase current window width" },
            { lhs = "W-", desc = "decrease current window width" },
        },
    },
    {
        title = "Editing",
        entries = {
            { lhs = "gf", desc = "open the file path under the cursor" },
            { lhs = "gF", desc = "open the file path under the cursor and jump to its line number" },
            { lhs = "insert jk", desc = "leave insert mode and land one character to the right" },
            { lhs = "select jk", desc = "leave select mode and land one character to the right" },
            { lhs = "visual <space>", desc = "leave visual mode" },
            { lhs = "visual J", desc = "move selected lines down" },
            { lhs = "visual K", desc = "move selected lines up" },
            { lhs = "<space>", desc = "toggle search highlighting on and off" },
            { lhs = "<leader>c", desc = "toggle fold under cursor" },
            { lhs = "<leader>'", desc = "wrap current word in single quotes" },
            { lhs = [[<leader>"]], desc = "wrap current word in double quotes" },
            { lhs = "W'", desc = "wrap current WORD in single quotes" },
            { lhs = [[W"]], desc = "wrap current WORD in double quotes" },
            { lhs = "gu", desc = "swap case on the current word" },
            { lhs = "gU", desc = "swap case on the current WORD" },
            { lhs = "dw", desc = "delete one word" },
            { lhs = "d2w", desc = "delete two words" },
            { lhs = "d3w", desc = "delete three words" },
            { lhs = "d4w", desc = "delete four words" },
            { lhs = "yw", desc = "yank one word" },
            { lhs = "cw", desc = "change one word" },
            { lhs = "<C-z>", desc = "disabled" },
        },
    },
    {
        title = "Git and Project Marks",
        notes = {
            "Use :Git to open Fugitive status. Inside :Git status, use - to stage or unstage, = to inspect diffs, cc to commit, ca to amend, p to push, P to pull, and q to close the window.",
            "Useful commands: :Git push, :Git pull, :Git fetch, :Git blame, :Gdiffsplit, :Gvdiffsplit, :Git log -- %, :0Gclog, :Git rebase -i HEAD~N.",
            "A git hunk is one contiguous changed block in the current file compared with Git.",
        },
        entries = {
            { lhs = ":Git", desc = "open Fugitive git status" },
            { lhs = "]h", desc = "jump to the next git hunk" },
            { lhs = "[h", desc = "jump to the previous git hunk" },
            { lhs = "<leader>gs", desc = "stage the current git hunk" },
            { lhs = "<leader>gr", desc = "reset the current git hunk" },
            { lhs = "<leader>gp", desc = "preview the current git hunk" },
            { lhs = "<leader>gb", desc = "show Git blame for the current line" },
            { lhs = "<leader>m", desc = "add current file to Harpoon" },
            { lhs = "<C-e>", desc = "toggle Harpoon quick menu" },
            { lhs = "<C-h>", desc = "jump to Harpoon file 1" },
            { lhs = "<C-j>", desc = "jump to Harpoon file 2" },
            { lhs = "<C-k>", desc = "jump to Harpoon file 3" },
            { lhs = "<C-l>", desc = "jump to Harpoon file 4" },
        },
    },
    {
        title = "Messages and Diagnostics",
        entries = {
            { lhs = "<leader>nd", desc = "dismiss Noice messages" },
            { lhs = "<leader>xx", desc = "toggle Trouble" },
            { lhs = "<leader>xw", desc = "Trouble workspace diagnostics" },
            { lhs = "<leader>xd", desc = "Trouble document diagnostics" },
            { lhs = "<leader>xq", desc = "Trouble quickfix list" },
            { lhs = "<leader>x]", desc = "Trouble location list" },
            { lhs = "<leader>xt", desc = "TODO comments in Trouble" },
            { lhs = "]d", desc = "jump to the next diagnostic or Trouble item" },
            { lhs = "[d", desc = "jump to the previous diagnostic or Trouble item" },
            { lhs = "]t", desc = "jump to the next TODO comment" },
            { lhs = "[t", desc = "jump to the previous TODO comment" },
            { lhs = "<leader>pt", desc = "TODO comments in Telescope" },
        },
    },
    {
        title = "LSP and Diagnostics",
        notes = {
            "These mappings only exist in buffers with an attached LSP client.",
            "Use <leader>vn for semantic symbol rename when you want only references to the current symbol changed.",
        },
        entries = {
            { lhs = "gd", desc = "go to definition" },
            { lhs = "K", desc = "hover documentation" },
            { lhs = "<leader>vw", desc = "workspace symbols" },
            { lhs = "<leader>vd", desc = "open diagnostic float" },
            { lhs = "<leader>vc", desc = "code action" },
            { lhs = "<leader>vr", desc = "references" },
            { lhs = "<leader>vn", desc = "rename the symbol under the cursor across project references" },
            { lhs = "<leader>r", desc = "show diagnostic float" },
            { lhs = "<leader>q", desc = "send diagnostics to the location list" },
            { lhs = "insert <C-h>", desc = "signature help" },
        },
    },
}

return M
